# Generated by Django 4.2.2 on 2023-07-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
