# Generated by Django 4.2.2 on 2023-06-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_menutype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="food_name",
            field=models.CharField(max_length=200),
        ),
    ]
